version: "3.3"
services:  
  pg-db:
    container_name: pg-db
    image: postgres:14.12-alpine3.18
    networks:
      - maianet
    environment:
      - POSTGRES_USER=maiau
      - POSTGRES_PASSWORD=maiapw
    ports:
      - 5432:5432  
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - 6379:6379


networks:
  maianet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
