version: "3.3"
services:  
  pg-db:
    container_name: pg-db
    image: postgres:14.12-alpine3.18
    networks:
      - maianet
    environment:
      - POSTGRES_USER=maiau
      - POSTGRES_PASSWORD=maiapw
    ports:
      - 5432:5432  
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server
    hostname: redis
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    user: "root:root"
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

    ports:
      - 9090:9090
    networks:
      - maianet


  grafana:
    image: grafana/grafana
    user: "root:root"
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - maianet
    depends_on:
      - prometheus


networks:
  maianet:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
  prometheus_data:
